default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 5432
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_development

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_production
